server:
  port: 8080
  servlet:
    context-path: /mysecurity
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/users?useSSL=true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update